Repository kimjinmyeong/django-ad-project, pull requests merged in 2023-05, with the labels that each got.

#5 refactor: `vote_views.py` 코드 리팩토링
  pybo/urls.py
  pybo/views/vote_views.py
  templates/pybo/question_detail.html
Labels: refactor

#7 refactor: comment view 파일들과 `page_views.py` 파일 베이스 수정
  pybo/views/comment_answer_view.py
  pybo/views/comment_question_view.py
  pybo/views/page_views.py
Labels: refactor

#8 질문 댓글 페이징, 정렬, 검색 기능 구현
  pybo/views/page_views.py
  templates/pybo/question_detail.html
Labels: feature

#10 refactor: `question_detail.html`
  templates/pybo/question_detail.html
Labels: refactor

#11 refactor: URI의 단어들을 복수 명사로 수정
  pybo/urls.py
Labels: refactor

#15 fix: 각 모델에 primary key 명시
  pybo/models.py
Labels: fix

#16 refactor: voter를 추가하는 로직을 유효성 검사 메소드에서 분리
  pybo/views/vote_views.py
Labels: refactor

#19 feat: 질문 및 `modify_counter` 관련 테스트 코드 추가
  pybo/migrations/0001_initial.py
  pybo/migrations/0002_answer_modify_counter_comment_modify_counter_and_more.py
  pybo/migrations/0002_question_author.py
  pybo/migrations/0003_answer_author.py
  pybo/migrations/0004_auto_20200507_1149.py
  pybo/migrations/0005_comment.py
  pybo/migrations/0006_auto_20200507_1449.py
  pybo/tests.py
Labels: feature
